export const EXERCISE_LABELS = {
  BENCH_PRESS: 'Bench Press',
  INCLINE_BENCH_PRESS: 'Incline Bench Press',
  DECLINE_BENCH_PRESS: 'Decline Bench Press',
  DUMBBELL_CHEST_PRESS: 'Dumbbell Chest Press',
  PUSH_UPS: 'Push-Ups',
  CHEST_DIPS: 'Chest Dips',
  CABLE_FLYS: 'Cable Flys',
  PEC_DECK_MACHINE: 'Pec Deck Machine',
  DUMBBELL_PULLOVER: 'Dumbbell Pullover',
  PULL_UPS: 'Pull-Ups',
  CHIN_UPS: 'Chin-Ups',
  BARBELL_BENT_OVER_ROW: 'Barbell Bent-Over Row',
  DUMBBELL_ROW: 'Dumbbell Row',
  DEADLIFT: 'Deadlift',
  T_BAR_ROW: 'T-Bar Row',
  SEATED_CABLE_ROW: 'Seated Cable Row',
  LAT_PULLDOWN: 'Lat Pulldown',
  REVERSE_FLYS: 'Reverse Flys',
  OVERHEAD_PRESS: 'Overhead Press',
  DUMBBELL_SHOULDER_PRESS: 'Dumbbell Shoulder Press',
  ARNOLD_PRESS: 'Arnold Press',
  LATERAL_RAISE: 'Lateral Raise',
  FRONT_RAISE: 'Front Raise',
  REAR_DELT_FLY: 'Rear Delt Fly',
  FACE_PULL: 'Face Pull',
  SHRUGS: 'Shrugs',
  BARBELL_CURL: 'Barbell Curl',
  DUMBBELL_CURL: 'Dumbbell Curl',
  HAMMER_CURL: 'Hammer Curl',
  PREACHER_CURL: 'Preacher Curl',
  CONCENTRATION_CURL: 'Concentration Curl',
  TRICEP_PUSHDOWN: 'Tricep Pushdown',
  SKULL_CRUSHERS: 'Skull Crushers',
  OVERHEAD_TRICEP_EXTENSION: 'Overhead Tricep Extension',
  CLOSE_GRIP_BENCH_PRESS: 'Close Grip Bench Press',
  TRICEP_DIPS: 'Tricep Dips',
  SQUAT: 'Squat',
  FRONT_SQUAT: 'Front Squat',
  LEG_PRESS: 'Leg Press',
  LUNGES: 'Lunges',
  BULGARIAN_SPLIT_SQUAT: 'Bulgarian Split Squat',
  GOBLET_SQUAT: 'Goblet Squat',
  LEG_EXTENSION: 'Leg Extension',
  ROMANIAN_DEADLIFT: 'Romanian Deadlift',
  LEG_CURL: 'Leg Curl',
  GOOD_MORNING: 'Good Morning',
  HIP_THRUST: 'Hip Thrust',
  GLUTE_BRIDGE: 'Glute Bridge',
  KETTLEBELL_SWING: 'Kettlebell Swing',
  STANDING_CALF_RAISE: 'Standing Calf Raise',
  SEATED_CALF_RAISE: 'Seated Calf Raise',
  PLANK: 'Plank',
  CRUNCHES: 'Crunches',
  SIT_UPS: 'Sit-Ups',
  RUSSIAN_TWIST: 'Russian Twist',
  HANGING_LEG_RAISE: 'Hanging Leg Raise',
  CABLE_CRUNCH: 'Cable Crunch',
  MOUNTAIN_CLIMBERS: 'Mountain Climbers',
  WRIST_CURL: 'Wrist Curl',
  REVERSE_WRIST_CURL: 'Reverse Wrist Curl',
  FARMER_CARRY: 'Farmer Carry',
  REVERSE_CURL: 'Reverse Curl',
  PLATE_PINCH: 'Plate Pinch',
};

export const getExerciseLabel = (exercise) =>
  EXERCISE_LABELS[exercise] || exercise?.replace(/_/g, ' ') || '';
